feat: assign asset
getwithashish/ExAM pull request #20
Opened 2024-02-21 14:02 UTC by Pavithra820

Created an API endpoint for assigning an asset to an employee.

2024-02-21 15:17 UTC, getwithashish requested changes
Please make the necessary changes.

2024-02-21 15:17 UTC, getwithashish commented on exam_django/asset/serializers/AssignAssetSerializer.py
> +
Is this serializer really required?
I couldn't find it being used anywhere.

2024-02-21 15:17 UTC, getwithashish commented on exam_django/asset/urls.py
> +
Please format using black.

2024-02-21 18:58 UTC, Pavithra820 commented on exam_django/asset/serializers/AssignAssetSerializer.py
> +
Removed all the blank spaces.

2024-02-21 18:58 UTC, Pavithra820 commented on exam_django/asset/serializers/AssignAssetSerializer.py
> +
Deleted the serializer

2024-02-21 18:58 UTC, Pavithra820 commented on exam_django/asset/urls.py
> +
Formatted the code using black formatter.

2024-02-21 19:00 UTC, Pavithra820 commented on exam_django/asset/urls.py
> +    path("assignasset/", AssignAssetView.as_view(),name="assignasset")
Changed the endpoint to assign_asset

2024-02-21 19:00 UTC, Pavithra820 commented on exam_django/asset/views/AssignAssetView.py
> +from rest_framework import status
Removed duplicated imports and unnecessary comments.

2024-02-22 06:41 UTC, getwithashish commented on exam_django/asset/serializers/AssignAssetSerializer.py
> +
Thank you

2024-02-22 06:41 UTC, getwithashish commented on exam_django/asset/serializers/AssignAssetSerializer.py
> +
Thank you for the update.

2024-02-22 06:41 UTC, getwithashish commented on exam_django/asset/urls.py
> +
Okay.

2024-02-22 10:36 UTC, getwithashish approved these changes
LGTM

2024-02-22 10:37 UTC, merged