Email styling
getwithashish/ExAM pull request #294
Opened 2024-05-22 10:58 UTC by Ashi941

2024-05-31 11:56 UTC, getwithashish requested changes

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/asset_approve_service/asset_approve_service.py
> +        print("Asset type is",asset_category)
Could you please remove the print() statements.

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/asset_approve_service/asset_approve_service.py
> +        print("Asset type is",asset_category)
Please remove the print() statements

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/asset_assign_service/assign_asset_service.py
> +from asset.service.asset_assign_service.asset_lead_role_assignasset_service import AssetLeadRoleAssignService
Please remove this import. I have removed this import in an earlier PR since Lead cannot assign an asset.

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/asset_assign_service/assign_asset_service.py
> +            )
Please remove this block of code. I have removed this block of code in an earlier PR since Lead cannot assign an asset.

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/email_format_services/lead_asset_allocation.py
Delete this file if not required

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/email_format_services/lead_asset_creation.py
Delete this file if not required

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/email_format_services/lead_asset_deallocate.py
Delete this file if not required

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/email_format_services/lead_asset_modification.py
Delete this file if not required

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/views/asset_unassign_view.py
> +                print(custodian_id)
Please remove the print() statements

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/views/asset_unassign_view.py
> +                    role, asset_uuid, requester,custodian_id=custodian_id
Is custodian_id required here?

2024-05-31 11:56 UTC, getwithashish commented on exam_django/asset/service/asset_crud_service/asset_mutation_service.py
Is this change here required?

2024-06-03 04:15 UTC, Ashi941 commented on exam_django/asset/views/asset_unassign_view.py
> +                    role, asset_uuid, requester,custodian_id=custodian_id
yes 
to print from whom the asset has been unassigned.

2024-06-07 12:13 UTC, getwithashish approved these changes

2024-06-07 12:14 UTC, merged